#!/bin/bash

STUNNELDIR=$HOME/stunnel

cd $STUNNELDIR

# Fix perms of certs or stunnel won't use them
chmod 0600 *.pem

# Sometimes the mirror is down and we have a broken stunnel
test -x /usr/bin/stunnel4 || { echo "stunnel4 not found!"; exit 1; }

# Client won't have this var (and won't need it)
test -z "$PORT_STUNNEL" && PORT_STUNNEL=10000

# Generate stunnel configs
# NOTE: The very last argument is the port your "client" listens on localhost for
# plaintext connections. You need one of these lines with a unique config_prefix
# (first arg) for each one. And, of course, local client port (last arg)
# needs to be unique as well.
./gen-stunnel-cfgs.py example 127.0.0.1:2222 "$PORT_STUNNEL" \
    "$DOTCLOUD_SERVER_STUNNEL_HOST:$DOTCLOUD_SERVER_STUNNEL_PORT" 4444

# Generate s3cmd config
./gen-s3cfg.py

# Download priv and pubkey
s3cmd --config=$STUNNELDIR/s3cmd.cfg --force get "$STUNNEL_S3_PRIVKEYPATH" $STUNNELDIR/key.pem
chmod 0600 $STUNNELDIR/key.pem

s3cmd --config=$STUNNELDIR/s3cmd.cfg --force get "$STUNNEL_S3_PUBKEYPATH" $STUNNELDIR/cert.pem
chmod 0600 $STUNNELDIR/cert.pem

